# Generated by Django 5.1.7 on 2025-03-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='InventarioCarga',
        ),
    ]
