# Generated by Django 5.1.7 on 2025-03-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0002_rename_inventario_inventariocarga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='decripcion',
            new_name='descripcion',
        ),
    ]
