# Generated by Django 5.1.7 on 2025-03-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0003_rename_decripcion_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carga',
            name='observaciones',
        ),
    ]
