# Generated by Django 5.1.7 on 2025-03-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0004_remove_carga_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocarga',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargas.producto'),
        ),
    ]
