# Generated by Django 5.1.7 on 2025-03-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0005_alter_inventariocarga_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='nombre',
            field=models.CharField(default=2, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
