# Generated by Django 5.1.7 on 2025-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0006_carga_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
