# Generated by Django 5.1.7 on 2025-03-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0007_carga_archivo_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='remision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
