# Generated by Django 5.1.7 on 2025-03-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0008_carga_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='remision',
            field=models.IntegerField(default=0),
        ),
    ]
