# Generated by Django 5.1.7 on 2025-03-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0009_alter_carga_remision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='remision',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
