# Generated by Django 5.1.7 on 2025-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0010_alter_carga_remision'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
