# Generated by Django 5.1.7 on 2025-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0011_carga_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
