# Generated by Django 5.1.7 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0012_alter_carga_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
