# Generated by Django 5.1.7 on 2025-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0013_alter_carga_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariocarga',
            name='codigo_barras',
            field=models.ImageField(blank=True, upload_to='codigos_barras/'),
        ),
    ]
