# Generated by Django 5.1.7 on 2025-04-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0014_inventariocarga_codigo_barras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carga',
            old_name='observacion',
            new_name='observaciones',
        ),
    ]
