# Generated by Django 5.1.7 on 2025-04-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0015_rename_observacion_carga_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariocarga',
            name='codigo_barras',
        ),
    ]
