# Generated by Django 5.1.7 on 2025-05-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0016_remove_inventariocarga_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariocarga',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventariocarga',
            name='fecha_generacion_codigo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
