# Generated by Django 5.1.7 on 2025-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0017_inventariocarga_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariocarga',
            name='info_legible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
