# Generated by Django 5.1.7 on 2025-04-02 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargas', '0014_inventariocarga_codigo_barras'),
        ('clientes', '0004_remove_cliente_archivo_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guia', models.CharField(blank=True, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('BODEGA', 'En bodega'), ('RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='BODEGA', max_length=10)),
                ('valor_flete', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='despachos.despacho')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargas.inventariocarga')),
            ],
            options={
                'unique_together': {('despacho', 'inventario')},
            },
        ),
    ]
