# Generated by Django 5.1.7 on 2025-04-03 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdespacho',
            options={'verbose_name_plural': 'Items de despacho'},
        ),
        migrations.AlterUniqueTogether(
            name='itemdespacho',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(choices=[('BODEGA', 'En bodega'), ('RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='BODEGA', max_length=20),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='valor_flete',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemdespacho',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemdespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='despachos.despacho'),
        ),
    ]
