# Generated by Django 5.1.7 on 2025-04-22 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0016_remove_inventariocarga_codigo_barras'),
        ('despachos', '0002_alter_itemdespacho_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdespacho',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_despacho', to='cargas.inventariocarga'),
        ),
    ]
