# Generated by Django 5.1.7 on 2025-05-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0003_alter_itemdespacho_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='valor_flete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
