# Generated by Django 5.1.7 on 2025-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0004_alter_despacho_valor_flete'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='placa_camion',
            field=models.CharField(default='', max_length=20),
        ),
    ]
