# Generated by Django 5.1.7 on 2025-05-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0005_despacho_placa_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='nombre_conductor',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
