# Generated by Django 5.1.7 on 2025-05-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0006_despacho_nombre_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespacho',
            name='velor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
