# Generated by Django 5.1.7 on 2025-05-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0007_itemdespacho_velor_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdespacho',
            old_name='velor_unitario',
            new_name='valor_unitario',
        ),
    ]
