# Generated by Django 5.1.7 on 2025-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0008_rename_velor_unitario_itemdespacho_valor_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdespacho',
            options={},
        ),
    ]
