# Generated by Django 5.1.7 on 2025-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0009_alter_itemdespacho_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='escaneo_completado',
            field=models.BooleanField(default=False),
        ),
    ]
