# Generated by Django 5.1.7 on 2025-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0010_despacho_escaneo_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespacho',
            name='escaneado',
            field=models.BooleanField(default=False),
        ),
    ]
