# Generated by Django 5.1.7 on 2025-05-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despachos', '0011_itemdespacho_escaneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdespacho',
            name='cantidad_escaneada',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
