# Generated by Django 5.1.7 on 2025-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='archivo_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
