# Generated by Django 5.1.7 on 2025-03-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_archivo_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='archivo_factura',
        ),
    ]
