# Generated by Django 5.1.7 on 2025-03-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
