# Generated by Django 5.1.7 on 2025-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_contacto_proveedor_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
